import { Dimensions, StyleSheet } from 'react-native';
import type { ThemeColors } from '../../constants/theme';

export function getStyles(c: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.surface,
    },
    scrollContent: {
      flexGrow: 1,
      alignItems: 'center',
      paddingHorizontal: 28,
      paddingTop: 20,
      paddingBottom: 40,
    },
    headerRow: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      marginTop: 12,
      marginBottom: 10,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: c.surface,
    },
    logoContainer: {
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: c.surface,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 36,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.10,
      shadowRadius: 8,
      elevation: 6,
    },
    logoImage: {
      width: 160,
      height: 160,
      backgroundColor: c.surface,
      borderRadius: 80,
      overflow: 'hidden',
      alignSelf: 'center',
    },
    mainTitle: {
      fontSize: 22,
      fontWeight: '600',
      color: c.text,
      textAlign: 'center',
      lineHeight: 30,
      marginBottom: 6,
    },
    highlightText: {
      color: '#E2A53B',
      fontWeight: '700',
    },
    subTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: c.text,
      textAlign: 'center',
      marginBottom: 24,
    },
    greetingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      flexWrap: 'wrap',
    },
    greetingText: {
      fontSize: 14,
      fontWeight: '500',
      color: c.text,
      textAlign: 'center',
    },
    waveEmoji: {
      marginLeft: 6,
    },
    introParagraph: {
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      lineHeight: 19,
      paddingHorizontal: 12,
      marginBottom: 28,
    },
    featurePill: {
      width: '100%',
      backgroundColor: c.background,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: c.border,
      paddingVertical: 14,
      paddingHorizontal: 20,
      marginBottom: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    featureText: {
      fontSize: 13,
      color: c.text,
      textAlign: 'center',
      lineHeight: 18,
      fontWeight: '400',
    },
    // Theme picker
    themeSection: {
      width: '100%',
      marginTop: 20,
      marginBottom: 8,
    },
    themeSectionLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: c.textMuted,
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      textAlign: 'center',
      marginBottom: 12,
    },
    themeRow: {
      flexDirection: 'row',
      gap: 10,
    },
    themeOption: {
      flex: 1,
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 16,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: c.border,
      backgroundColor: c.background,
    },
    themeOptionActive: {
      borderColor: '#D35400',
      backgroundColor: c.surface,
    },
    themeOptionLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: c.textMuted,
    },
    themeOptionLabelActive: {
      color: '#D35400',
    },
    // CTA
    actionContainer: {
      width: '100%',
      marginTop: 20,
    },
    getStartedButton: {
      width: '100%',
      height: 52,
      borderRadius: 26,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 8,
      backgroundColor: '#D35400',
    },
    getStartedText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
}
